server:
  port: 8080

spring:
  application:
    name: tripgg-backend
  
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&readOnly=false&autoCommit=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      read-only: false
      auto-commit: true
      connection-init-sql: SET SESSION TRANSACTION READ WRITE
      connection-test-query: SELECT 1
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        connection:
          read_only: false
        jdbc:
          batch_size: 20
        transaction:
          jta:
            timeout: 30
  
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /static/**
  
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}

logging:
  level:
    com.tripgg: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# 카카오 설정
kakao:
  # 로그인 설정
  client-id: ${KAKAO_CLIENT_ID}
  client-secret: ${KAKAO_CLIENT_SECRET}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  
  # 맵 API 설정
  map:
    api:
      key: ${KAKAO_MAP_API_KEY}
      base-url: https://dapi.kakao.com
