name: Maven CI & Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest
    environment: TripGG-Back-Deploy   # 사용할 Environment 이름

    steps:
      # 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # JDK 설정 (Java 17 예시)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # application.yml 생성
      - name: Make application.yml
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml

      # Maven 빌드
      - name: Build with Maven
        run: mvn clean package -DskipTests
      # Docker 빌드
      - name: Build Docker image
        run: docker build -t tripgg:latest .

      # Docker Save (tar.gz 파일 생성)
      - name: Save Docker image as tar
        run: |
          docker save tripgg:latest | gzip > tripgg.tar.gz

      # SFTP로 빌드 결과 서버 전송
      - name: Upload JAR via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: tripgg.tar.gz
          target: /home/${{ secrets.SERVER_USER }}/app/

      # SSH로 서버에서 Docker 실행
      - name: Run Docker on server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/app
            gzip -d  tripgg.tar.gz
            docker load -i tripgg.tar
            docker stop tripgg || true
            docker rm tripgg || true
            docker run -d --name tripgg -p 8080:8080 tripgg:latest